print('Что сказал колобок, когда вышел с бани?')
input()
print('Забыл голову помыть!')
print()
print('Тук-тук')
input()
print('Whо там?')
input()
print('Невежливая корова')
input()
print('Невежливая корова?', end='')
print('-МУУУУУ!')
